live_config_reload = true

[window]
padding = { x=3, y=3 }
opacity = 0.7
startup_mode = "Fullscreen"
blur = true

[mouse]
hide_when_typing = true

[scrolling]
history = 1000

[font]
size = 11
normal.family = "JetBrainsMono Nerd Font"

[shell]
program = "fish"
args = ["-l", "-c", "tmux attach || tmux"]

