[window]
padding = { x=3, y=3 }
startup_mode = "Fullscreen"
opacity = 0.9
blur = true

[mouse]
hide_when_typing = true

[shell]
program = "/bin/fish"

[scrolling]
history = 1000

[font]
normal = { family = "FiraCode Nerd Font", style = "Normal" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

