live_config_reload = true
[window]
padding = { x=3, y=3 }
startup_mode = "Maximized"
opacity = 0.9
blur = true

[mouse]
hide_when_typing = true

[scrolling]
history = 1000

[font]
size = 11
normal.family = "JetBrainsMono Nerd Font"
